// packages/react/src/providers/config.tsx
import { createConfig, type Config, createSelectors } from '@quirks/store';
import {
  type PropsWithChildren,
  createContext,
  useContext,
  useRef,
} from 'react';

export type QuirksConfigState = ReturnType<typeof createConfig>;

export const QuirksConfigContext = createContext<QuirksConfigState | undefined>(
  undefined,
);

export interface QuirksConfigProps {
  config?: Config;
}

export const QuirksConfig = (props: PropsWithChildren<QuirksConfigProps>) => {
  const { children, config: configOptions } = props;
  const storeRef = useRef<QuirksConfigState>();

  if (!configOptions) {
    throw new Error(
      ['`config` must be setup within `QuirksConfig`.'].join('\n'),
    );
  }

  if (!storeRef.current) {
    storeRef.current = createConfig(configOptions);
  }

  return (
    <QuirksConfigContext.Provider value={storeRef.current}>
      {children}
    </QuirksConfigContext.Provider>
  );
};

export const useQuirks = () => {
  const store = useContext(QuirksConfigContext);

  if (!store) {
    throw new Error(
      ['`useQuirks` must be used within `QuirksConfig`.'].join('\n'),
    );
  }

  return createSelectors(store);
};

// packages/vue/src/providers/config.vue
<script setup lang="ts">
import { provide, readonly } from 'vue';
import { ConfigStateSymbol, type QuirksConfigProps } from './config';
import { createConfig } from '@quirks/store';

const props = defineProps<QuirksConfigProps>();

if (!props.config) {
  throw new Error(['`config` must be setup within `QuirksConfig`.'].join('\n'));
}

const store = createConfig(props.config);

provide(ConfigStateSymbol, readonly(store));
</script>

<template>
  <slot></slot>
</template>
